apiVersion: v1
kind: ConfigMap
metadata:
  name: envoy-worker-config
data:
  envoy.yaml: |
    admin:
      access_log_path: /dev/null
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 20002
    dynamic_resources:
      cds_config:
        resource_api_version: V3
        api_config_source:
          api_type: GRPC
          transport_api_version: V3
          grpc_services:
          - envoy_grpc:
              cluster_name: xds_cluster
          set_node_on_first_message_only: true
      lds_config:
        resource_api_version: V3
        api_config_source:
          api_type: GRPC
          transport_api_version: V3
          grpc_services:
          - envoy_grpc:
              cluster_name: xds_cluster
          set_node_on_first_message_only: true
    node:
      cluster: k8s-cluster
      id: sidecar
    static_resources:
      listeners:
      - name: worker_ng_control
        reuse_port: true
        address:
          socket_address:
            protocol: UDP
            address: 0.0.0.0
            port_value: 1998
        listener_filters:
          name: envoy.filters.udp_listener.udp_proxy
          typed_config:
            '@type': type.googleapis.com/envoy.extensions.filters.udp.udp_proxy.v3.UdpProxyConfig
            stat_prefix: service
            cluster: worker_ng_control_cluster
      clusters:
      - name: xds_cluster
        connect_timeout: 1s
        type: STRICT_DNS
        http2_protocol_options: {}
        load_assignment:
          cluster_name: xds_cluster
          endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: envoy-controlplane.default.svc
                    port_value: 18000
      - name: worker_ng_control_cluster
        connect_timeout: 0.25s
        type: STRICT_DNS
        lb_policy: ROUND_ROBIN
        load_assignment:
          cluster_name: worker_ng_control_cluster
          endpoints:
            - lb_endpoints:
                - endpoint:
                    address:
                      socket_address:
                        address: 127.0.0.1
                        port_value: 2000
    layered_runtime:
      layers:
        - name: runtime-0
          rtds_layer:
            rtds_config:
              resource_api_version: V3
              api_config_source:
                transport_api_version: V3
                api_type: GRPC
                grpc_services:
                  envoy_grpc:
                    cluster_name: xds_cluster
            name: runtime-0
---
# worker
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  labels:
    app: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      volumes:
        - name: envoy-config-volume
          configMap:
            name: envoy-worker-config
        - name: rtpengine-config-volume
          configMap:
            name: rtpengine-config
        - name: kernel-debug
          hostPath:
            path: /sys/kernel/debug
            type: Directory
      containers:
        # sidecar
        - name: envoy-worker
          image: envoyproxy/envoy:v1.17-latest
          imagePullPolicy: Always
          command: [ "envoy" ]
          args: ["-c", "/etc/envoy/envoy.yaml", "-l", "trace"]
          ports:
            - containerPort: 1998
              name: ng-control
            - containerPort: 19000
              name: rtp-a
            - containerPort: 19001
              name: rtcp-a
            - containerPort: 19002
              name: rtp-b
            - containerPort: 19003
              name: rtcp-b
          volumeMounts:
            - name: envoy-config-volume
              mountPath: /etc/envoy
        - name: rtpengine
          image: drachtio/rtpengine
          imagePullPolicy: IfNotPresent
          # command: ["/bin/sh"]
          # args: ["-c", "while true; do echo hello; sleep 10;done"]
          command: [ "/usr/local/bin/rtpengine" ]
          args: [ "--config-file=/etc/rtpengine/rtpengine.conf", "-i", "lo", "-f", "-L", "7", "-E" ]
          volumeMounts:
            - name: rtpengine-config-volume
              mountPath: /etc/rtpengine
        - name: net-debug
          image: l7mp/net-debug:0.5.3
        - name: rtpe-operator
          image: vidarhun/rtpe-operator
          env:
            - name: RTPE_OPERATOR
              value: "envoy"
            - name: RTPE_ADDRESS
              value: "127.0.0.1"
            - name: RTPE_PORT
              value: "22222"
            - name: WITHOUT_JSONSOCKET
              value: "yes"
            - name: ENVOY_MGM_ADDRESS
              value: "envoy-controlplane"
            - name: ENVOY_MGM_PORT
              value: "1234"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rtpengine-config
  namespace: default
data:
  rtpengine.conf: |
    [rtpengine]
    # access only via the sidecar proxy
    # listen-ng=MY_IP:22222
    # interface=MY_IP
    listen-ng=127.0.0.1:22222
    interface=lo

    foreground=true
    log-stderr=true

    port-min=10000
    port-max=20000

    recording-dir=/tmp
    recording-method=pcap
    recording-format=eth

    log-level=7
    delete-delay=0

    timeout=600

    # redis = 127.0.0.1:6379/5
    # redis-write = password@12.23.34.45:6379/42
    # redis-num-threads = 8
    # no-redis-required = false
    # redis-expires = 86400
    # redis-allowed-errors = -1
    # redis-disable-time = 10
    # redis-cmd-timeout = 0
    # redis-connect-timeout = 1000
    # sip-source = false
    # dtls-passive = false
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: worker
  name: worker
spec:
  ports:
    - port: 19000
      name: worker-rtp-a-service-port
      protocol: UDP
      targetPort: 19000
    - port: 19001
      name: worker-rtcp-a-service-port
      protocol: UDP
      targetPort: 19001
    - port: 19002
      name: worker-rtp-b-service-port
      protocol: UDP
      targetPort: 19002
    - port: 19003
      name: worker-rtcp-b-service-port
      protocol: UDP
      targetPort: 19003
    - port: 1998
      name: udp-rtpengine-ng-port
      protocol: UDP
      targetPort: 1998
  selector:
    app: worker
  type: ClusterIP